version: 1.0.1
rules:
  - match: ^【高清影视之家发布\s*www\.HDBTHD\.com】(.*?)(?:\[.*?\]*)\..*?((?:20|19)\d{2}).*?$
    rename: "$1 ($2)"
    junk:
      - 【高清影视之家发布 www.HDBTHD.com】【高清影视之家发布 www.HDBTHD.com】
      - 【更多无水印蓝光原盘请访问 www.HDBTHD.com】【更多无水印蓝光原盘请访问 www.HDBTHD.com】

  - match: ^【高清剧集网发布\s*www\.DDHDTV\.com】(.*?)(?:\[.*?\]*)\..*?(S\d{2}).*?((?:20|19)\d{2}).*?$
    rename: "$1 ($3)/$2"
    junk:
      - 【更多电视剧集下载请访问 www.DDHDTV.com】【更多剧集打包下载请访问 www.DDHDTV.com】
      - 【更多高清剧集下载请访问 www.DDHDTV.com】【更多剧集打包下载请访问 www.DDHDTV.com】

