version: 1.0.1
junk:
  - 【更多电视剧集下载请访问 www.DDHDTV.com】【更多剧集打包下载请访问 www.DDHDTV.com】
  - 【更多高清剧集下载请访问 www.DDHDTV.com】【更多剧集打包下载请访问 www.DDHDTV.com】
  - 【更多无水印蓝光原盘请访问 www.BBQDDQ.com】【更多无水印蓝光原盘请访问 www.BBQDDQ.com】
# destination: /home/rogee/projects/btrenamer/t
destination: /medias

# 『 不太灵免费影视站 www.butailing.com 』
rules:
  - match:
      - ^(?:【.*?】)?(.*?)(?:\[.*?\]*)\..*?(S\d{2}).*?((?:20|19)\d{2}).*?$
      - ^(?:『.*?』)?(.*?)(?:\[.*?\]*)\..*?(S\d{2}).*?((?:20|19)\d{2}).*?$
    rename: "$1 ($3)/$2"
    dir: tv

  - match:
      - ^(?:【.*?】)?(.*?)(?:\[.*?\]*)\..*?((?:20|19)\d{2}).*?$
      - ^(?:『.*?』)?(.*?)(?:\[.*?\]*)\..*?((?:20|19)\d{2}).*?$
    rename: "$1 ($2)"
    dir: movie
